### ISSUE TITLE
Use Blue-Green Deployment to Reduce Downtime and Risk

### ISSUE THREAD

**Issue by idugalic** [ivans-innovation-lab/my-company-monolithic-web#5]
Reference this great article by @marcingrzejszczak https://spring.io/blog/2016/05/31/zero-downtime-deployment-with-a-database.

- Introduce DB schema versioning first.
- Create two production environments on PWS: blue, green and prepare your scripts
- We have only one DB instance for both environments. Make sure that you document how the process of DB migration (to the next version) should look like, so you are 'backward compatible' (at least one release back). This way you can do a rollback if needed.

**Comment by marcingrzejszczak** [comment]
Check out how we do this testing in Spring Cloud Pipelines :) With Cloud Foundry it's extremely simple 

(kind of pseudo code)

```bash
function performGreenDeploymentOfTestedApplication() {
    local appName="${1}"
    local newName="${appName}-venerable"
    echo "Renaming the app from [${appName}] -> [${newName}]"
    local appPresent="no"
    cf app "${appName}" && appPresent="yes"
    if [[ "${appPresent}" == "yes" ]]; then
        cf rename "${appName}" "${newName}"
    else
        echo "Will not rename the application cause it's not there"
    fi
    deployAndRestartApp
}

function deleteBlueInstance() {
    local appName=$( retrieveAppName )
    # Log in to CF to start deployment
    logInToPaas
    local oldName="${appName}-venerable"
    echo "Deleting the app [${oldName}]"
    cf app "${oldName}" && appPresent="yes"
    if [[ "${appPresent}" == "yes" ]]; then
        cf delete "${oldName}" -f
    else
        echo "Will not remove the old application cause it's not there"
    fi
}
```

**Comment by idugalic** [comment]
I will. Thanks @marcingrzejszczak

**Comment by idugalic** [comment]
This is done. Only on Monolith app. Microservices are going to be a challenge  :)
